version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
